export const AUTH_ERROR_CODES = {
  DISALLOWED_DOMAIN: "DISALLOWED_DOMAIN",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  PASSWORD_NOT_SET: "PASSWORD_NOT_SET"
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
