export const TRUST_EVENT_TYPES = [
  "PAID_CANCELLATION",
  "REFUND_ISSUED",
  "SELLER_NO_SHOW",
  "BUYER_NO_SHOW",
  "ISSUE_REPORTED",
  "CONVERSATION_REPORTED",
  "USER_BLOCKED",
  "RELIST_AFTER_FAILED_HANDOFF",
  "DUPLICATE_CHECKOUT_BLOCKED"
] as const;

export type TrustEventTypeValue = (typeof TRUST_EVENT_TYPES)[number];

export const TrustEventTypeValues = {
  PAID_CANCELLATION: "PAID_CANCELLATION",
  REFUND_ISSUED: "REFUND_ISSUED",
  SELLER_NO_SHOW: "SELLER_NO_SHOW",
  BUYER_NO_SHOW: "BUYER_NO_SHOW",
  ISSUE_REPORTED: "ISSUE_REPORTED",
  CONVERSATION_REPORTED: "CONVERSATION_REPORTED",
  USER_BLOCKED: "USER_BLOCKED",
  RELIST_AFTER_FAILED_HANDOFF: "RELIST_AFTER_FAILED_HANDOFF",
  DUPLICATE_CHECKOUT_BLOCKED: "DUPLICATE_CHECKOUT_BLOCKED"
} as const satisfies Record<TrustEventTypeValue, TrustEventTypeValue>;

export const TRANSACTION_ISSUE_TYPES = [
  "ITEM_NOT_RECEIVED",
  "ITEM_NOT_AS_DESCRIBED",
  "WRONG_ITEM",
  "DAMAGED_OR_POOR_CONDITION",
  "SELLER_NO_SHOW",
  "BUYER_NO_SHOW",
  "LAST_MINUTE_CANCELLATION",
  "OTHER"
] as const;

export type TransactionIssueTypeValue = (typeof TRANSACTION_ISSUE_TYPES)[number];
